[uwsgi]
uid = uwsgi
gid = uwsgi
module = bmrbdep
plugins = python3
http = :9001
master = true
cheaper = 1
workers = 10
http-timeout = 3600
socket-timeout = 3600

# Make more room for headers
buffer-size=65535

# These fix the path issue
#route-run = setpathinfo:${SCRIPT_NAME}${PATH_INFO}
#route-run = setscriptname:
